//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBClient.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class address
    {
        public int Id_Address { get; set; }
        public string Street { get; set; }
        public string StreetNumber { get; set; }
        public string Plz { get; set; }
        public string Location { get; set; }
        public string IsoCountry { get; set; }
    }
}
