//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBClient.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer
    {
        public int ID_Customer { get; set; }
        public string Name { get; set; }
        public Nullable<int> ID_InvoiceAddress { get; set; }
        public int ID_Address { get; set; }
        public Nullable<int> InvoiceThreshold { get; set; }
    }
}
