//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBClient.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class deviceprinter
    {
        public int ID_DeviceType { get; set; }
        public string resolution { get; set; }
        public Nullable<decimal> pagesPerMinute { get; set; }
        public Nullable<bool> isColorPrinter { get; set; }
    }
}
