//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBClient.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class devicetype
    {
        public int ID_DeviceType { get; set; }
        public int ID_DeviceCategory { get; set; }
        public string Manufacturer { get; set; }
        public string ManufacturerNumber { get; set; }
        public int NumInterfaces { get; set; }
        public Nullable<int> ID_Rate { get; set; }
        public int ID_MediumType { get; set; }
        public string Description { get; set; }
    }
}
