//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBClient.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class device
    {
        public int ID_Device { get; set; }
        public int ID_DeviceType { get; set; }
        public int ID_Location { get; set; }
        public string Hostname { get; set; }
        public string SerialNumber { get; set; }
        public Nullable<bool> IsPhysical { get; set; }
    }
}
