//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBClient.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class InventarEntities : DbContext
    {
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<address> address { get; set; }
        public DbSet<communication> communication { get; set; }
        public DbSet<communicationtype> communicationtype { get; set; }
        public DbSet<credential> credential { get; set; }
        public DbSet<customer> customer { get; set; }
        public DbSet<device> device { get; set; }
        public DbSet<devicecategory> devicecategory { get; set; }
        public DbSet<devicemachine> devicemachine { get; set; }
        public DbSet<deviceprinter> deviceprinter { get; set; }
        public DbSet<devicerouter> devicerouter { get; set; }
        public DbSet<deviceswitch> deviceswitch { get; set; }
        public DbSet<devicetype> devicetype { get; set; }
        public DbSet<devicewlanaccesspoint> devicewlanaccesspoint { get; set; }
        public DbSet<invoice> invoice { get; set; }
        public DbSet<invoiceposition> invoiceposition { get; set; }
        public DbSet<location> location { get; set; }
        public DbSet<log> log { get; set; }
        public DbSet<mediumtype> mediumtype { get; set; }
        public DbSet<networkinterface> networkinterface { get; set; }
        public DbSet<payment> payment { get; set; }
        public DbSet<person> person { get; set; }
        public DbSet<pod> pod { get; set; }
        public DbSet<rate> rate { get; set; }
        public DbSet<reldevicecredential> reldevicecredential { get; set; }
        public DbSet<relnetworkinterface> relnetworkinterface { get; set; }
        public DbSet<relnetworkinterfacevlan> relnetworkinterfacevlan { get; set; }
        public DbSet<servicetype> servicetype { get; set; }
        public DbSet<unit> unit { get; set; }
        public DbSet<vlan> vlan { get; set; }
        public DbSet<wlanstandard> wlanstandard { get; set; }
        public DbSet<v_usageperlocation> v_usageperlocation { get; set; }
        public DbSet<v_usageperpod> v_usageperpod { get; set; }
        public DbSet<v_invoices> v_invoices { get; set; }
    
        public virtual int P_NightlyInvoicing()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_NightlyInvoicing");
        }
    
        public virtual int P_PodBill(Nullable<int> id_pod)
        {
            var id_podParameter = id_pod.HasValue ?
                new ObjectParameter("id_pod", id_pod) :
                new ObjectParameter("id_pod", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_PodBill", id_podParameter);
        }
    }
}
