//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBClient.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class invoiceposition
    {
        public int ID_InvoicePosition { get; set; }
        public int ID_Invoice { get; set; }
        public Nullable<int> ID_ServiceType { get; set; }
        public decimal Amount { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Description { get; set; }
        public Nullable<int> ID_Networkinterface { get; set; }
        public Nullable<int> ID_Device { get; set; }
        public Nullable<int> ID_Location { get; set; }
    }
}
