//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBClient.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class location
    {
        public int ID_Location { get; set; }
        public int ID_Pod { get; set; }
        public int ID_Address { get; set; }
        public Nullable<int> ID_ParentLocation { get; set; }
        public string Description { get; set; }
    }
}
