//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBClient.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class log
    {
        public int ID_Log { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<int> Severity { get; set; }
        public string Message { get; set; }
        public int ID_Device { get; set; }
        public int Acknowledged { get; set; }
    }
}
