//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBClient.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class networkinterface
    {
        public int ID_Networkinterface { get; set; }
        public Nullable<bool> Physical { get; set; }
        public Nullable<long> IPv4_Address { get; set; }
        public byte[] IPv6_Address { get; set; }
        public int ID_Device { get; set; }
        public Nullable<int> PortNr { get; set; }
        public Nullable<int> ID_MediumType { get; set; }
        public string Description { get; set; }
        public Nullable<int> IPv4_SubnetMask { get; set; }
        public Nullable<int> IPv4_DefaultGateway { get; set; }
        public string IPv6_DefaultGateway { get; set; }
    }
}
