//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBClient.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class payment
    {
        public int ID_Payment { get; set; }
        public int ID_Customer { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime PaymentDate { get; set; }
    }
}
