//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBClient.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class rate
    {
        public int ID_Rate { get; set; }
        public Nullable<int> ID_ServiceType { get; set; }
        public Nullable<int> ID_Unit { get; set; }
        public decimal Price { get; set; }
        public System.DateTime ValidFrom { get; set; }
        public Nullable<System.DateTime> ValidTo { get; set; }
    }
}
