//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBClient.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vlan
    {
        public int ID_Vlan { get; set; }
        public int ID_Location { get; set; }
        public int Identifier { get; set; }
        public Nullable<long> RangeStartIP4 { get; set; }
        public byte[] RangeStartIP6 { get; set; }
        public Nullable<long> RangeLength6 { get; set; }
    }
}
